
USE TMD
GO

CREATE PROCEDURE CC.USP_SOLICITUD_INS
@TIPO_SOLICITUD CHAR(1),
@DESCRIPCION VARCHAR(300),
@NUMERO_BUENA_PRO VARCHAR(15),
@NUMERO_CARTA_FIANZA VARCHAR(15),
@RAZON_SOCIAL_CLIENTE VARCHAR(100),
@RUC_CLIENTE CHAR(11),
@DIRECCION_CLIENTE VARCHAR(200),
@TELEFONO_CLIENTE VARCHAR(20),
@ANEXO_CLIENTE VARCHAR(5),
@CORREO_CLIENTE VARCHAR(50),
@FAX_CLIENTE VARCHAR(15),
@TIPO_CLIENTE CHAR(1),
@CODIGO_CONTRATO INT,
@NUMERO_SOLICITUD CHAR(10) OUT
AS
	DECLARE @CORRELATIVO INT

	IF(@TIPO_SOLICITUD='R') SET @CODIGO_CONTRATO=NULL
	SET @CORRELATIVO=(SELECT CORRELATIVO FROM CC.TABLA_CORRELATIVO WHERE NOMBRE_TABLA='SOLICITUD')+1
	SET @NUMERO_SOLICITUD='SOL' + RIGHT('0000000'+CONVERT(VARCHAR(7),@CORRELATIVO),7)

	INSERT INTO SOLICITUD
			   ([NUMERO_SOLICITUD]
			   ,[TIPO_SOLICITUD]
			   ,[DESCRIPCION]
			   ,[NUMERO_BUENA_PRO]
			   ,[NUMERO_CARTA_FIANZA]
			   ,[RAZON_SOCIAL_CLIENTE]
			   ,[RUC_CLIENTE]
			   ,[DIRECCION_CLIENTE]
			   ,[TELEFONO_CLIENTE]
			   ,[ANEXO_CLIENTE]
			   ,[CORREO_CLIENTE]
			   ,[FAX_CLIENTE]
			   ,[TIPO_CLIENTE]
			   ,[CODIGO_CONTRATO])
		 VALUES
			   (@NUMERO_SOLICITUD, 
				@TIPO_SOLICITUD, 
				@DESCRIPCION, 
				@NUMERO_BUENA_PRO, 
				@NUMERO_CARTA_FIANZA, 
				@RAZON_SOCIAL_CLIENTE, 
				@RUC_CLIENTE, 
				@DIRECCION_CLIENTE, 
				@TELEFONO_CLIENTE, 
				@ANEXO_CLIENTE, 
				@CORREO_CLIENTE, 
				@FAX_CLIENTE,
				@TIPO_CLIENTE, 
				@CODIGO_CONTRATO)
	UPDATE CC.TABLA_CORRELATIVO SET CORRELATIVO=@CORRELATIVO WHERE NOMBRE_TABLA='SOLICITUD'
GO


CREATE PROCEDURE CC.USP_SOLICITUD_UPD
@CODIGO_SOLICITUD INT,
@DESCRIPCION VARCHAR(300),
@NUMERO_BUENA_PRO VARCHAR(15),
@NUMERO_CARTA_FIANZA VARCHAR(15),
@RAZON_SOCIAL_CLIENTE VARCHAR(100),
@RUC_CLIENTE CHAR(11),
@DIRECCION_CLIENTE VARCHAR(200),
@TELEFONO_CLIENTE VARCHAR(20),
@ANEXO_CLIENTE VARCHAR(5),
@CORREO_CLIENTE VARCHAR(50),
@FAX_CLIENTE VARCHAR(15),
@TIPO_CLIENTE CHAR(1)
AS

	UPDATE CC.SOLICITUD SET	DESCRIPCION = @DESCRIPCION,
							NUMERO_BUENA_PRO = @NUMERO_BUENA_PRO,
							NUMERO_CARTA_FIANZA =@NUMERO_CARTA_FIANZA,
							RAZON_SOCIAL_CLIENTE = @RAZON_SOCIAL_CLIENTE,
							RUC_CLIENTE = @RUC_CLIENTE,
							DIRECCION_CLIENTE = @DIRECCION_CLIENTE,
							TELEFONO_CLIENTE = @TELEFONO_CLIENTE,
							ANEXO_CLIENTE = @ANEXO_CLIENTE,
							CORREO_CLIENTE = @CORREO_CLIENTE,
							FAX_CLIENTE = @FAX_CLIENTE,
							TIPO_CLIENTE = @TIPO_CLIENTE							
	WHERE CODIGO_SOLICITUD = @CODIGO_SOLICITUD
GO


CREATE PROCEDURE CC.USP_SOLICITUD_DEL
@CODIGO_SOLICITUD INT
AS
	DELETE CC.SOLICITUD WHERE CODIGO_SOLICITUD = @CODIGO_SOLICITUD
GO



CREATE PROCEDURE CC.USP_SOLICITUD_SEL
@TIPO_SOLICITUD CHAR(1)
AS
--(CASE TIPO_SOLICITUD WHEN 'R' THEN 'REQUERIMIENTO', ELSE 'CAMBIO' END)
	IF(@TIPO_SOLICITUD='R')
		SELECT CODIGO_SOLICITUD, NUMERO_SOLICITUD, 'REQUERIMIENTO' AS TIPO_SOLICITUD, 
				DESCRIPCION, RAZON_SOCIAL_CLIENTE AS DATO_ADICIONAL, MOTIVO_RECHAZO, 
				(CASE ESTADO WHEN 'P' THEN 'PENDIENTE' WHEN 'A' THEN 'APROBADO' ELSE 'RECHAZADO' END) AS ESTADO 
		FROM CC.SOLICITUD 
		WHERE TIPO_SOLICITUD = 'R'
	ELSE
		SELECT S.CODIGO_SOLICITUD, NUMERO_SOLICITUD, 'CAMBIO' AS TIPO_SOLICITUD, 
				DESCRIPCION, NUMERO_DOCUMENTO AS DATO_ADICIONAL, MOTIVO_RECHAZO, 
				(CASE S.ESTADO WHEN 'P' THEN 'PENDIENTE' WHEN 'A' THEN 'APROBADO' ELSE 'RECHAZADO' END) AS ESTADO 
		FROM CC.SOLICITUD S INNER JOIN CONTRATO C ON S.CODIGO_CONTRATO = C.CODIGO_CONTRATO
		WHERE TIPO_SOLICITUD = 'C'
GO

CREATE PROCEDURE CC.USP_SOLICITUD_GET
@CODIGO_SOLICITUD INT
AS
		SELECT NUMERO_BUENA_PRO, NUMERO_CARTA_FIANZA, RAZON_SOCIAL_CLIENTE, RUC_CLIENTE, 
				DIRECCION_CLIENTE, TELEFONO_CLIENTE, ANEXO_CLIENTE, CORREO_CLIENTE, 
				FAX_CLIENTE, TIPO_CLIENTE
		FROM CC.SOLICITUD	
		WHERE CODIGO_SOLICITUD = @CODIGO_SOLICITUD
GO


CREATE PROCEDURE CC.USP_CONTRATOS_ACTIVOS
AS
	SELECT CODIGO_CONTRATO, NUMERO_DOCUMENTO FROM CC.CONTRATO WHERE ESTADO ='A'
GO