CREATE TABLE MONEDA (
	CODIGO_MONEDA CHAR ( 3 ) NOT NULL,
	NOMBRE VARCHAR ( 20 ) NOT NULL,
	CONSTRAINT UQ_MONEDA_NOMBRE UNIQUE NONCLUSTERED (NOMBRE),
	CONSTRAINT PK_MONEDA PRIMARY KEY NONCLUSTERED (CODIGO_MONEDA)
	)
GO
CREATE TABLE CONTRATO_INDICADOR (
	VALOR_OBJETIVO VARCHAR ( 20 ) NOT NULL,
	VALOR_ALCANZADO VARCHAR ( 20 ),
	ESTADO CHAR ( 1 ) NOT NULL,
	CODIGO_CONTRATO INT NOT NULL,
	CODIGO_INDICADOR INT NOT NULL,
	CONSTRAINT PK_CONTRATO_INDICADOR PRIMARY KEY NONCLUSTERED (CODIGO_INDICADOR, CODIGO_CONTRATO),
	CONSTRAINT CK_CONTRATO_INDICADOR_ESTADO CHECK (ESTADO IN('P','C','I'))
	)
GO
CREATE TABLE PENALIDAD (
	CODIGO_PENALIDAD CHAR ( 7 ) NOT NULL,
	DESCRIPCION VARCHAR ( 50 ) NOT NULL,
	PORCENTAJE DECIMAL ( 5, 2 ) NOT NULL,
	ESTADO BIT DEFAULT 1 NOT NULL,
	CODIGO_TIPO_PENALIDAD INT NOT NULL,
	CONSTRAINT PK_PENALIDAD PRIMARY KEY NONCLUSTERED (CODIGO_PENALIDAD)
	)
GO
CREATE TABLE CONTRATO_ROL (
	CODIGO_CONTRATO INT NOT NULL,
	CODIGO_ROL INT NOT NULL,
	CONSTRAINT PK_CONTRATO_ROL PRIMARY KEY NONCLUSTERED (CODIGO_ROL, CODIGO_CONTRATO)
	)
GO
CREATE TABLE INCUMPLIMIENTO (
	CODIGO_INCUMPLIMIENTO INT IDENTITY NOT NULL,
	DESCRIPCION VARCHAR ( 200 ) NOT NULL,
	FECHA DATETIME NOT NULL,
	ESTADO CHAR ( 1 ) DEFAULT 'P' NOT NULL,
	CODIGO_CONTRATO INT NOT NULL,
	CONSTRAINT PK_INCUMPLIMIENTO PRIMARY KEY NONCLUSTERED (CODIGO_INCUMPLIMIENTO),
	CONSTRAINT CK_INCUMPLIMIENTO_ESTADO CHECK (ESTADO IN('P','A','R'))
	)
GO
CREATE TABLE TIPO_CONTRATO (
	CODIGO_TIPO_CONTRATO INT IDENTITY NOT NULL,
	DESCRIPCION VARCHAR ( 50 ) NOT NULL,
	CONSTRAINT UQ_TIPO_CONTRATO_DESCRIPCION UNIQUE NONCLUSTERED (DESCRIPCION),
	CONSTRAINT PK_TIPO_CONTRATO PRIMARY KEY NONCLUSTERED (CODIGO_TIPO_CONTRATO)
	)
GO
CREATE TABLE CONTRATO (
	CODIGO_CONTRATO INT IDENTITY NOT NULL,
	NUMERO_DOCUMENTO CHAR ( 10 ) NOT NULL,
	TIPO_DOCUMENTO CHAR ( 1 ) NOT NULL,
	ARCHIVO_ADJUNTO VARCHAR ( 200 ) NOT NULL,
	FECHA_INICIO DATETIME NOT NULL,
	FECHA_FIN DATETIME NOT NULL,
	TIPO_CAMBIO MONEY,
	MONTO_MONEDA_NACIONAL MONEY NOT NULL,
	MONTO_MONEDA_EXTRANJERA MONEY,
	GARANTIA VARCHAR ( 1000 ) NOT NULL,
	BONIFICACION VARCHAR ( 1000 ) NOT NULL,
	ESTADO CHAR ( 1 ) DEFAULT 'P' NOT NULL,
	FECHA_TERMINO DATETIME,
	MOTIVO_TERMINO VARCHAR ( 200 ),
	CODIGO_SOLICITUD INT NOT NULL,
	CODIGO_CLIENTE INT NOT NULL,
	CODIGO_TIPO_CONTRATO INT NOT NULL,
	CODIGO_SERVICIO INT NOT NULL,
	CODIGO_MONEDA CHAR ( 3 ) NOT NULL,
	CODIGO_CONTRATO_PADRE INT NOT NULL,
	CONSTRAINT UQ_CONTRATO_NUMERO_DOCUMENTO UNIQUE NONCLUSTERED (NUMERO_DOCUMENTO),
	CONSTRAINT PK_CONTRATO PRIMARY KEY NONCLUSTERED (CODIGO_CONTRATO),
	CONSTRAINT CK_CONTRATO_TIPO_DOCUMENTO CHECK (TIPO_DOCUMENTO IN ('C','A')),
	CONSTRAINT CK_CONTRATO_ESTADO CHECK (ESTADO IN ('P','A','C','N'))
	)
GO
CREATE TABLE INDICADOR (
	CODIGO_INDICADOR INT IDENTITY NOT NULL,
	DESCRIPCION VARCHAR ( 50 ) NOT NULL,
	FRECUENCIA CHAR ( 1 ) NOT NULL,
	CONSTRAINT UQ_INDICADOR_DESCRIPCION UNIQUE NONCLUSTERED (DESCRIPCION),
	CONSTRAINT PK_INDICADOR PRIMARY KEY NONCLUSTERED (CODIGO_INDICADOR)
	)
GO
CREATE TABLE CONTRATO_CLAUSULA (
	CODIGO_CONTRATO INT NOT NULL,
	CODIGO_CLAUSULA CHAR ( 7 ) NOT NULL,
	CONSTRAINT PK_CONTRATO_CLAUSULA PRIMARY KEY NONCLUSTERED (CODIGO_CLAUSULA, CODIGO_CONTRATO)
	)
GO
CREATE TABLE LINEA_SERVICIO (
	CODIGO_LINEA_SERVICIO INT IDENTITY NOT NULL,
	DESCRIPCION VARCHAR ( 50 ) NOT NULL,
	CONSTRAINT PK_LINEA_SERVICIO PRIMARY KEY NONCLUSTERED (CODIGO_LINEA_SERVICIO),
	CONSTRAINT UQ_LINEA_SERVICIO_DESCRIPCION UNIQUE NONCLUSTERED (DESCRIPCION)
	)
GO
CREATE TABLE ROL (
	CODIGO_ROL INT IDENTITY NOT NULL,
	NOMBRE VARCHAR ( 25 ) NOT NULL,
	CONSTRAINT PK_ROL PRIMARY KEY NONCLUSTERED (CODIGO_ROL),
	CONSTRAINT UQ_ROL_NOMBRE UNIQUE NONCLUSTERED (NOMBRE)
	)
GO
CREATE TABLE CLAUSULA (
	CODIGO_CLAUSULA CHAR ( 7 ) NOT NULL,
	TIPO_CLAUSULA CHAR ( 1 ) NOT NULL,
	DESCRIPCION_CORTA VARCHAR ( 50 ) NOT NULL,
	DESCRIPCION_LARGA VARCHAR ( 500 ) NOT NULL,
	CONSTRAINT PK_CLAUSULA PRIMARY KEY NONCLUSTERED (CODIGO_CLAUSULA),
	CONSTRAINT CK_CLAUSULA_TIPO_CLAUSULA CHECK (TIPO_CLAUSULA IN('G','S'))
	)
GO
CREATE TABLE INCUMPLIMIENTO_CONTRATO_PENALIDAD (
	CODIGO_INCUMPLIMIENTO INT NOT NULL,
	CODIGO_PENALIDAD CHAR ( 7 ) NOT NULL,
	CODIGO_CONTRATO INT NOT NULL,
	CONSTRAINT PK_INCUMPLIMIENTO_CONTRATO_PENALIDAD PRIMARY KEY NONCLUSTERED (CODIGO_PENALIDAD, CODIGO_CONTRATO, CODIGO_INCUMPLIMIENTO)
	)
GO
CREATE TABLE CLIENTE (
	CODIGO_CLIENTE INT IDENTITY NOT NULL,
	RAZON_SOCIAL VARCHAR ( 100 ) NOT NULL,
	RUC CHAR ( 11 ) NOT NULL,
	DIRECCION VARCHAR ( 200 ) NOT NULL,
	TELEFONO VARCHAR ( 20 ) NOT NULL,
	ANEXO VARCHAR ( 5 ),
	CORREO VARCHAR ( 50 ) NOT NULL,
	FAX VARCHAR ( 15 ),
	TIPO_PERSONA CHAR ( 1 ) NOT NULL,
	TIPO_CLIENTE CHAR ( 1 ) NOT NULL,
	ESTADO BIT DEFAULT 1 NOT NULL,
	CONSTRAINT UQ_CLIENTE_RAZON_SOCIAL UNIQUE NONCLUSTERED (RAZON_SOCIAL),
	CONSTRAINT PK_CLIENTE PRIMARY KEY NONCLUSTERED (CODIGO_CLIENTE),
	CONSTRAINT UQ_CLIENTE_RUC UNIQUE NONCLUSTERED (RUC),
	CONSTRAINT CK_CLIENTE_TIPO_CLIENTE CHECK (TIPO_CLIENTE IN ('P','R')),
	CONSTRAINT CK__CLIENTE_TIPO_PERSONA CHECK (TIPO_PERSONA IN ('N','J'))
	)
GO
CREATE TABLE ENTREGABLE (
	CODIGO_ENTREGABLE INT IDENTITY NOT NULL,
	DESCRIPCION VARCHAR ( 100 ) NOT NULL,
	FECHA_PACTADA DATETIME NOT NULL,
	RESPONSABLE VARCHAR ( 100 ),
	FECHA_ENTREGA DATETIME,
	CARGO VARCHAR ( 15 ),
	ESTADO BIT DEFAULT 0 NOT NULL,
	CODIGO_CONTRATO INT NOT NULL,
	CONSTRAINT PK_ENTREGABLE PRIMARY KEY NONCLUSTERED (CODIGO_ENTREGABLE)
	)
GO
CREATE TABLE SERVICIO (
	CODIGO_SERVICIO INT IDENTITY NOT NULL,
	DESCRIPCION VARCHAR ( 50 ) NOT NULL,
	CODIGO_LINEA_SERVICIO INT NOT NULL,
	CONSTRAINT PK_SERVICIO PRIMARY KEY NONCLUSTERED (CODIGO_SERVICIO),
	CONSTRAINT UQ_SERVICIO_DESCRIPCION UNIQUE NONCLUSTERED (DESCRIPCION)
	)
GO
CREATE TABLE INCUMPLIMIENTO_CONTRATO_CLAUSULA (
	CODIGO_INCUMPLIMIENTO INT NOT NULL,
	CODIGO_CLAUSULA CHAR ( 7 ) NOT NULL,
	CODIGO_CONTRATO INT NOT NULL,
	CONSTRAINT PK_INCUMPLIMIENTO_CONTRATO_CLAUSULA PRIMARY KEY NONCLUSTERED (CODIGO_CLAUSULA, CODIGO_CONTRATO, CODIGO_INCUMPLIMIENTO)
	)
GO
CREATE TABLE TIPO_PENALIDAD (
	CODIGO_TIPO_PENALIDAD INT IDENTITY NOT NULL,
	DESCRIPCION VARCHAR ( 20 ) NOT NULL,
	CONSTRAINT PK_TIPO_PENALIDAD PRIMARY KEY NONCLUSTERED (CODIGO_TIPO_PENALIDAD),
	CONSTRAINT UQ_TIPO_PENALIDAD_DESCRIPCION UNIQUE NONCLUSTERED (DESCRIPCION)
	)
GO
CREATE TABLE SOLICITUD (
	CODIGO_SOLICITUD INT IDENTITY NOT NULL,
	NUMERO_SOLICITUD CHAR ( 10 ) NOT NULL,
	TIPO_SOLICITUD CHAR ( 1 ) NOT NULL,
	DESCRIPCION VARCHAR ( 300 ) NOT NULL,
	NUMERO_BUENA_PRO VARCHAR ( 15 ),
	NUMERO_CARTA_FIANZA VARCHAR ( 15 ),
	RAZON_SOCIAL_CLIENTE VARCHAR ( 100 ),
	RUC_CLIENTE CHAR ( 11 ),
	DIRECCION_CLIENTE VARCHAR ( 200 ),
	TELEFONO_CLIENTE VARBINARY ( 20 ),
	ANEXO_CLIENTE VARBINARY ( 5 ),
	CORREO_CLIENTE VARCHAR ( 50 ),
	FAX_CLIENTE VARCHAR ( 15 ),
	TIPO_PERSONA CHAR ( 1 ),
	TIPO_CLIENTE CHAR ( 1 ),
	ESTADO CHAR ( 1 ) DEFAULT 'P' NOT NULL,
	MOTIVO_RECHAZO VARCHAR ( 150 ),
	CODIGO_CONTRATO INT NOT NULL,
	CONSTRAINT PK_SOLICITUD PRIMARY KEY NONCLUSTERED (CODIGO_SOLICITUD),
	CONSTRAINT UQ_SOLICITUD_NUMERO_SOLICITUD UNIQUE NONCLUSTERED (NUMERO_SOLICITUD),
	CONSTRAINT CK_SOLICITUD_TIPO_CLIENTE CHECK (TIPO_CLIENTE IN ('P','R')),
	CONSTRAINT CK_SOLICITUD_TIPO_PERSONA CHECK (TIPO_PERSONA IN ('N','J')),
	CONSTRAINT CK_SOLICITUD_ESTADO CHECK (ESTADO IN ('P','A','R')),
	CONSTRAINT CK_SOLICITUD_TIPO_SOLICITUD CHECK (TIPO_SOLICITUD IN ('R','C')
)
	)
GO
CREATE TABLE CONTRATO_PENALIDAD (
	CODIGO_CONTRATO INT NOT NULL,
	CODIGO_PENALIDAD CHAR ( 7 ) NOT NULL,
	CONSTRAINT PK_CONTRATO_PENALIDAD PRIMARY KEY NONCLUSTERED (CODIGO_PENALIDAD, CODIGO_CONTRATO)
	)
GO
ALTER TABLE CONTRATO_INDICADOR ADD CONSTRAINT FK_CONTRATO_INDICADOR_INDICADOR FOREIGN KEY (CODIGO_INDICADOR) REFERENCES INDICADOR (CODIGO_INDICADOR) 
GO
ALTER TABLE CONTRATO_INDICADOR ADD CONSTRAINT FK_CONTRATO_INDICADOR_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO (CODIGO_CONTRATO) 
GO
ALTER TABLE INCUMPLIMIENTO ADD CONSTRAINT FK_INCUMPLIMIENTO_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO (CODIGO_CONTRATO) 
GO
ALTER TABLE CONTRATO_CLAUSULA ADD CONSTRAINT FK_CONTRATO_CLAUSULA_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO (CODIGO_CONTRATO) 
GO
ALTER TABLE CONTRATO_CLAUSULA ADD CONSTRAINT FK_CONTRATO_CLAUSULA_CLAUSULA FOREIGN KEY (CODIGO_CLAUSULA) REFERENCES CLAUSULA (CODIGO_CLAUSULA) 
GO
ALTER TABLE PENALIDAD ADD CONSTRAINT FK_PENALIDAD_TIPO_PENALIDAD FOREIGN KEY (CODIGO_TIPO_PENALIDAD) REFERENCES TIPO_PENALIDAD (CODIGO_TIPO_PENALIDAD) 
GO
ALTER TABLE INCUMPLIMIENTO_CONTRATO_PENALIDAD ADD CONSTRAINT FK_INCUMPLIMIENTO_CONTRATO_PENALIDAD_INCUMPLIMIENTO FOREIGN KEY (CODIGO_INCUMPLIMIENTO) REFERENCES INCUMPLIMIENTO (CODIGO_INCUMPLIMIENTO) 
GO
ALTER TABLE INCUMPLIMIENTO_CONTRATO_PENALIDAD ADD CONSTRAINT FK_INCUMPLIMIENTO_CONTRATO_PENALIDAD_CONTRATO_PENALIDAD FOREIGN KEY (CODIGO_PENALIDAD, CODIGO_CONTRATO) REFERENCES CONTRATO_PENALIDAD (CODIGO_PENALIDAD, CODIGO_CONTRATO) 
GO
ALTER TABLE INCUMPLIMIENTO_CONTRATO_CLAUSULA ADD CONSTRAINT FK_INCUMPLIMIENTO_CONTRATO_CLAUSULA_INCUMPLIMIENTO FOREIGN KEY (CODIGO_INCUMPLIMIENTO) REFERENCES INCUMPLIMIENTO (CODIGO_INCUMPLIMIENTO) 
GO
ALTER TABLE INCUMPLIMIENTO_CONTRATO_CLAUSULA ADD CONSTRAINT FK_INCUMPLIMIENTO_CONTRATO_CLAUSULA_CONTRATO_CLAUSULA FOREIGN KEY (CODIGO_CLAUSULA, CODIGO_CONTRATO) REFERENCES CONTRATO_CLAUSULA (CODIGO_CLAUSULA, CODIGO_CONTRATO) 
GO
ALTER TABLE SERVICIO ADD CONSTRAINT FK_SERVICIO_LINEA_SERVICIO FOREIGN KEY (CODIGO_LINEA_SERVICIO) REFERENCES LINEA_SERVICIO (CODIGO_LINEA_SERVICIO) 
GO
ALTER TABLE CONTRATO_PENALIDAD ADD CONSTRAINT FK_CONTRATO_PENALIDAD_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO (CODIGO_CONTRATO) 
GO
ALTER TABLE CONTRATO_PENALIDAD ADD CONSTRAINT FK_CONTRATO_PENALIDAD_PENALIDAD FOREIGN KEY (CODIGO_PENALIDAD) REFERENCES PENALIDAD (CODIGO_PENALIDAD) 
GO
ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_SERVICIO FOREIGN KEY (CODIGO_SERVICIO) REFERENCES SERVICIO (CODIGO_SERVICIO) 
GO
ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE (CODIGO_CLIENTE) 
GO
ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_CONTRATO FOREIGN KEY (CODIGO_CONTRATO_PADRE) REFERENCES CONTRATO (CODIGO_CONTRATO) 
GO
ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_MONEDA FOREIGN KEY (CODIGO_MONEDA) REFERENCES MONEDA (CODIGO_MONEDA) 
GO
ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_TIPO_CONTRATO FOREIGN KEY (CODIGO_TIPO_CONTRATO) REFERENCES TIPO_CONTRATO (CODIGO_TIPO_CONTRATO) 
GO
ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_SOLICITUD FOREIGN KEY (CODIGO_SOLICITUD) REFERENCES SOLICITUD (CODIGO_SOLICITUD) 
GO
ALTER TABLE ENTREGABLE ADD CONSTRAINT FK_ENTREGABLE_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO (CODIGO_CONTRATO) 
GO
ALTER TABLE SOLICITUD ADD CONSTRAINT FK_SOLICITUD_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO (CODIGO_CONTRATO) 
GO
ALTER TABLE CONTRATO_ROL ADD CONSTRAINT FK_CONTRATO_ROL_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO (CODIGO_CONTRATO) 
GO
ALTER TABLE CONTRATO_ROL ADD CONSTRAINT FK_CONTRATO_ROL_ROL FOREIGN KEY (CODIGO_ROL) REFERENCES ROL (CODIGO_ROL) 
GO

